name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  compile:
    name: Compile

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v5
      - name: Setup Kaitai Struct compiler
        uses: jonahsnider/kaitai-action@v1.0.1
      - name: Compile schema
        run: kaitai-struct-compiler --target graphviz wpilog.ksy
  lint:
    name: Lint

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run ksylint
        run: test "$(ksylint wpilog.ksy)" = "$(cat ./expected_lint_output.txt)"
